apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flrnet
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cramkumar/argohelm.git
    path: charts/flrnet/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
